package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type fieldInfo struct {
	Name      string
	IsPtr     bool
	Algorithm string
	HasAlgo   bool
}

type structInfo struct {
	Name   string
	Fields []fieldInfo
}

var tmpl = template.Must(template.New("gasypt").Parse(`// Code generated by gasypt-gen. DO NOT EDIT.

package {{.PkgName}}

import "github.com/czyczk/gasypt-lite"

{{range .Structs}}
func (s *{{.Name}}) DecryptEncFields(password string) error {
	return s.DecryptEncFieldsWith(gasypt.PBEWithHMACSHA512AndAES_256, password)
}

func (s *{{.Name}}) DecryptEncFieldsWith(algo gasypt.Algorithm, password string) error {
	{{- range .Fields}}
	{
		{{- if .IsPtr}}
		if s.{{.Name}} != nil && gasypt.IsEncValue(*s.{{.Name}}) {
			{{- if .HasAlgo}}
			decrypted, err := gasypt.DecryptEncWith(gasypt.{{.Algorithm}}, *s.{{.Name}}, password)
			{{- else}}
			decrypted, err := gasypt.DecryptEncWith(algo, *s.{{.Name}}, password)
			{{- end}}
			if err != nil {
				return err
			}
			*s.{{.Name}} = decrypted
		}
		{{- else}}
		if gasypt.IsEncValue(s.{{.Name}}) {
			{{- if .HasAlgo}}
			decrypted, err := gasypt.DecryptEncWith(gasypt.{{.Algorithm}}, s.{{.Name}}, password)
			{{- else}}
			decrypted, err := gasypt.DecryptEncWith(algo, s.{{.Name}}, password)
			{{- end}}
			if err != nil {
				return err
			}
			s.{{.Name}} = decrypted
		}
		{{- end}}
	}
	{{- end}}
	return nil
}

func (s *{{.Name}}) ClearSensitiveFields() {
	{{- range .Fields}}
	{{- if .IsPtr}}
	if s.{{.Name}} != nil {
		*s.{{.Name}} = ""
	}
	{{- else}}
	gasypt.ClearString(&s.{{.Name}})
	{{- end}}
	{{- end}}
}
{{end}}
`))

type templateData struct {
	PkgName string
	Structs []structInfo
}

func main() {
	args := os.Args[1:]
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "Usage: gasypt-gen <file.go> [file.go ...]")
		os.Exit(1)
	}

	for _, inputPath := range args {
		if err := processFile(inputPath); err != nil {
			fmt.Fprintf(os.Stderr, "Error processing %s: %v\n", inputPath, err)
			os.Exit(1)
		}
	}
}

func processFile(inputPath string) error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, inputPath, nil, parser.ParseComments)
	if err != nil {
		return err
	}

	var structs []structInfo
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			si := structInfo{Name: typeSpec.Name.Name}
			for _, field := range st.Fields.List {
				tag := ""
				if field.Tag != nil {
					tag = field.Tag.Value
					tag = strings.Trim(tag, "`")
				}
				tagVal := extractTagValue(tag, "gasypt")
				if tagVal == "" || !strings.Contains(tagVal, "encrypted") {
					continue
				}

				for _, name := range field.Names {
					fi := fieldInfo{Name: name.Name}

					switch t := field.Type.(type) {
					case *ast.StarExpr:
						if ident, ok := t.X.(*ast.Ident); ok && ident.Name == "string" {
							fi.IsPtr = true
						}
					case *ast.Ident:
						if t.Name != "string" {
							continue
						}
					default:
						continue
					}

					if algo := parseAlgoFromTag(tagVal); algo != "" {
						fi.Algorithm = algo
						fi.HasAlgo = true
					}

					si.Fields = append(si.Fields, fi)
				}
			}

			if len(si.Fields) > 0 {
				structs = append(structs, si)
			}
		}
	}

	if len(structs) == 0 {
		return nil
	}

	data := templateData{
		PkgName: f.Name.Name,
		Structs: structs,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated code: %w\n\nGenerated:\n%s", err, buf.String())
	}

	ext := filepath.Ext(inputPath)
	base := strings.TrimSuffix(inputPath, ext)
	outputPath := base + "_gasypt.go"

	return os.WriteFile(outputPath, formatted, 0644)
}

func extractTagValue(tag, key string) string {
	search := key + ":\""
	idx := strings.Index(tag, search)
	if idx < 0 {
		return ""
	}
	start := idx + len(search)
	end := strings.IndexByte(tag[start:], '"')
	if end < 0 {
		return ""
	}
	return tag[start : start+end]
}

func parseAlgoFromTag(tagVal string) string {
	parts := strings.Split(tagVal, ",")
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if strings.HasPrefix(part, "algorithm=") {
			return strings.TrimPrefix(part, "algorithm=")
		}
	}
	return ""
}
